# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def generate_fibonnaci(max_val):
    if max_val < 1:
        return []
    fseq = [1, 2]
    if max_val == 1:
        return [fseq[0]]
    if max_val == 2:
        return fseq
    else:
        new_val = 3
        while new_val < max_val:
            fseq.append(new_val)
            new_val = sum(fseq[-2:])
    return fseq


fib = generate_fibonnaci(4*10**6)
answer = sum([f for f in fib if not f % 2])
print(f"Answer to problem 2: {answer}")
